'================================================== 
' Generated by DWRAD version 1.0.0.0
' Berak di celana
' TransTV

' Created Date: 3/13/2008 2:15:44 PM
' 


Public Class uiMstKategoriAsset
    Private Const mUiName As String = "Asset Category "
    Private Const SHOW_SAVE_CONFIRMATION As Boolean = True

    Private Event FormBeforeOpenRow(ByRef id As Object)
    Private Event FormAfterOpenRow(ByRef id As Object)
    Private Event FormBeforeSave(ByRef id As Object)
    Private Event FormAfterSave(ByRef id As Object, ByVal result As FormSaveResult)
    Private Event FormBeforeNew()
    Private Event FormBeforeDelete(ByRef id As Object)
    Private Event FormAfterDelete(ByRef id As Object)

    Private FILTER_QUERY_MODE As Boolean
    Private DATA_ISLOCKED As Boolean

    Private objFormError As Windows.Forms.ErrorProvider = New Windows.Forms.ErrorProvider

    Private tbl_MstKategoriasset As DataTable = CreateTblMstKategoriasset()
    Private tbl_MstKategoriasset_Temp As DataTable = CreateTblMstKategoriasset()
    Private tbl_MstKategoriassetpilihan As DataTable = clsDataset.CreateTblMstPilihan


#Region " Window Parameter "
    ' TODO: Buat variabel untuk menampung parameter window 

#End Region


#Region " Window Dataset "
    Public Shared Function CreateTblMstKategoriasset() As DataTable
        Dim tbl As DataTable = New DataTable

        tbl.Columns.Clear()
        tbl.Columns.Add(New DataColumn("kategoriasset_id", GetType(System.String)))
        tbl.Columns.Add(New DataColumn("kategoriasset_time", GetType(System.Int64)))
        tbl.Columns.Add(New DataColumn("kategoriasset_depresiasitime", GetType(System.String)))
        tbl.Columns.Add(New DataColumn("kategoriasset_depresiasivalue", GetType(System.Decimal)))


        '-------------------------------
        'Default Value: 
        tbl.Columns("kategoriasset_id").DefaultValue = ""
        tbl.Columns("kategoriasset_time").DefaultValue = 0
        tbl.Columns("kategoriasset_depresiasitime").DefaultValue = ""
        tbl.Columns("kategoriasset_depresiasivalue").DefaultValue = 0


        Return tbl
    End Function

#End Region


#Region " Overrides "

    Public Overrides Function btnQuery_Click() As Boolean
        Me.PnlDfSearch.Visible = Not Me.PnlDfSearch.Visible
        If Me.PnlDfSearch.Visible Then
            FILTER_QUERY_MODE = True
            Me.tbtnQuery.CheckState = CheckState.Checked
        Else
            FILTER_QUERY_MODE = False
            Me.tbtnQuery.CheckState = CheckState.Unchecked
        End If
        Return MyBase.btnQuery_Click()
    End Function

    Public Overrides Function btnNew_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        If Me.ftabMain.SelectedIndex = 0 Then
            Me.ftabMain.SelectedIndex = 1
        End If
        Me.uiMstKategoriAsset_NewData()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnNew_Click()
    End Function

    Public Overrides Function btnLoad_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstKategoriAsset_Retrieve()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnLoad_Click()
    End Function

    Public Overrides Function btnSave_Click() As Boolean
        If Me.uiMstKategoriAsset_FormError() Then
            Return True
        End If
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstKategoriAsset_Save()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnSave_Click()
    End Function


    Public Overrides Function btnPrint_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstKategoriAsset_Print()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnPrint_Click()
    End Function

    Public Overrides Function btnDel_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstKategoriAsset_Delete()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnDel_Click()
    End Function

    Public Overrides Function btnFirst_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstKategoriAsset_First()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnFirst_Click()
    End Function

    Public Overrides Function btnPrev_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstKategoriAsset_Prev()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnPrev_Click()
    End Function

    Public Overrides Function btnNext_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstKategoriAsset_Next()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnNext_Click()
    End Function

    Public Overrides Function btnLast_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstKategoriAsset_Last()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnLast_Click()
    End Function


#End Region


#Region " Layout & Init UI "

    Private Function FormatDgvMstKategoriasset(ByRef objDgv As System.Windows.Forms.DataGridView) As Boolean
        ' Format DgvMstKategoriasset Columns 
        Dim cKategoriasset_id As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Dim cKategoriasset_time As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Dim cKategoriasset_depresiasitime As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Dim cKategoriasset_depresiasivalue As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn

        cKategoriasset_id.Name = "kategoriasset_id"
        cKategoriasset_id.HeaderText = "Category"
        cKategoriasset_id.DataPropertyName = "kategoriasset_id"
        cKategoriasset_id.Width = 350
        cKategoriasset_id.Visible = True
        cKategoriasset_id.ReadOnly = False

        cKategoriasset_time.Name = "kategoriasset_time"
        cKategoriasset_time.HeaderText = "Annual"
        cKategoriasset_time.DataPropertyName = "kategoriasset_time"
        cKategoriasset_time.Width = 100
        cKategoriasset_time.Visible = True
        cKategoriasset_time.ReadOnly = False

        cKategoriasset_depresiasitime.Name = "kategoriasset_depresiasitime"
        cKategoriasset_depresiasitime.HeaderText = "Time"
        cKategoriasset_depresiasitime.DataPropertyName = "kategoriasset_depresiasitime"
        cKategoriasset_depresiasitime.Width = 100
        cKategoriasset_depresiasitime.Visible = True
        cKategoriasset_depresiasitime.ReadOnly = False

        cKategoriasset_depresiasivalue.Name = "kategoriasset_depresiasivalue"
        cKategoriasset_depresiasivalue.HeaderText = "Value"
        cKategoriasset_depresiasivalue.DataPropertyName = "kategoriasset_depresiasivalue"
        cKategoriasset_depresiasivalue.Width = 100
        cKategoriasset_depresiasivalue.Visible = False
        cKategoriasset_depresiasivalue.ReadOnly = False

        objDgv.Columns.Clear()
        objDgv.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() _
        {cKategoriasset_id, cKategoriasset_time, cKategoriasset_depresiasitime, cKategoriasset_depresiasivalue})



        ' DgvMstKategoriasset Behaviours: 
        objDgv.AllowUserToAddRows = False
        objDgv.AllowUserToDeleteRows = False
        objDgv.AllowUserToResizeRows = False
        objDgv.ReadOnly = True
        objDgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect

    End Function

    Private Function InitLayoutUI() As Boolean

        Me.ftabMain.Anchor = AnchorStyles.Bottom
        Me.ftabMain.Anchor += AnchorStyles.Top
        Me.ftabMain.Anchor += AnchorStyles.Right
        Me.ftabMain.Anchor += AnchorStyles.Left

        Me.ftabMain.TabPages.Item(1).BackColor = Color.Gainsboro
        Me.PnlDfSearch.Dock = DockStyle.Top
        Me.PnlDfSearch.Visible = False
        Me.PnlDfMain.Dock = DockStyle.Fill
        Me.DgvMstKategoriasset.Dock = DockStyle.Fill

        Me.FormatDgvMstKategoriasset(Me.DgvMstKategoriasset)

    End Function

    Private Function BindingStop() As Boolean
        'stop binding
        Me.obj_Kategoriasset_id.DataBindings.clear()
        Me.obj_Kategoriasset_time.DataBindings.clear()
        Me.obj_Kategoriasset_depresiasitime.DataBindings.clear()
        Me.obj_Kategoriasset_depresiasivalue.DataBindings.clear()
        Return True
    End Function

    Private Function BindingStart() As Boolean
        'start binding
        Me.obj_Kategoriasset_id.DataBindings.Add(New Binding("Text", Me.tbl_MstKategoriasset_Temp, "kategoriasset_id"))
        Me.obj_Kategoriasset_time.DataBindings.Add(New Binding("Text", Me.tbl_MstKategoriasset_Temp, "kategoriasset_time"))
        Me.obj_Kategoriasset_depresiasitime.DataBindings.Add(New Binding("SelectedValue", Me.tbl_MstKategoriasset_Temp, "kategoriasset_depresiasitime"))
        Me.obj_Kategoriasset_depresiasivalue.DataBindings.Add(New Binding("Text", Me.tbl_MstKategoriasset_Temp, "kategoriasset_depresiasivalue", True, DataSourceUpdateMode.OnPropertyChanged, 0, "#,##0.00"))
        Return True
    End Function

#End Region


#Region " Dialoged Control "
#End Region


#Region " User Defined Function "

    Private Function uiMstKategoriAsset_NewData() As Boolean
        'new data
        RaiseEvent FormBeforeNew()

        ' TODO: Set Default Value for tbl_MstKategoriasset_Temp
        Me.tbl_MstKategoriasset_Temp.Clear()




        Me.BindingContext(Me.tbl_MstKategoriasset_Temp).EndCurrentEdit()
        Try
            Me.BindingContext(Me.tbl_MstKategoriasset_Temp).AddNew()
        Catch ex As Exception
            MessageBox.Show(ex.Source)
        End Try

    End Function

    Private Function uiMstKategoriAsset_Retrieve() As Boolean
        'retrieve data
        Dim criteria As String = ""

        ' TODO: Parse Criteria using clsProc.RefParser()


        Me.tbl_MstKategoriasset.Clear()
        Try
            Me.DataFill(Me.tbl_MstKategoriasset, "as_MstKategoriasset_Select", criteria)
        Catch ex As Exception
            MsgBox(ex.Message)
        End Try

    End Function

    Private Function uiMstKategoriAsset_Save() As Boolean
        'save data
        Dim tbl_MstKategoriasset_Temp_Changes As DataTable
        Dim success As Boolean
        Dim kategoriasset_id As Object = New Object
        Dim i As Integer = 0
        Dim MasterDataState As System.Data.DataRowState
        Dim result As FormSaveResult

        Me.Cursor = Cursors.WaitCursor
        RaiseEvent FormBeforeSave(kategoriasset_id)

        Me.BindingContext(Me.tbl_MstKategoriasset_Temp).EndCurrentEdit()
        tbl_MstKategoriasset_Temp_Changes = Me.tbl_MstKategoriasset_Temp.GetChanges()

        If tbl_MstKategoriasset_Temp_Changes IsNot Nothing Then

            Try

                MasterDataState = tbl_MstKategoriasset_Temp.Rows(0).RowState
                kategoriasset_id = tbl_MstKategoriasset_Temp.Rows(0).Item("kategoriasset_id")

                If tbl_MstKategoriasset_Temp_Changes IsNot Nothing Then
                    success = Me.uiMstKategoriAsset_SaveMaster(kategoriasset_id, tbl_MstKategoriasset_Temp_Changes, MasterDataState)
                    If Not success Then Throw New Exception("Error: Saving Master Data at Me.uiMstKategoriAsset_SaveMaster(tbl_MstKategoriasset_Temp_Changes)")
                    Me.tbl_MstKategoriasset_Temp.AcceptChanges()
                End If

                result = FormSaveResult.SaveSuccess
                If SHOW_SAVE_CONFIRMATION Then
                    MessageBox.Show("Data Saved", mUiName, MessageBoxButtons.OK, MessageBoxIcon.Information)
                End If

            Catch ex As Exception
                result = FormSaveResult.SaveError
                MessageBox.Show("Data Cannot Be Saved" & vbcrlf & ex.Message, mUiName, MessageBoxButtons.OK, MessageBoxIcon.Error)
            End Try

        Else
            result = FormSaveResult.Nochanges
            If SHOW_SAVE_CONFIRMATION Then
                MessageBox.Show("All changes has been saved", mUiName, MessageBoxButtons.OK, MessageBoxIcon.Information)
            End If
        End If

        RaiseEvent FormAfterSave(kategoriasset_id, result)
        Me.Cursor = Cursors.Arrow

    End Function

    Private Function uiMstKategoriAsset_SaveMaster(ByRef kategoriasset_id As Object, ByVal objTbl As DataTable, ByVal MasterDataState As System.Data.DataRowState) As Boolean
        Dim dbConn As OleDb.OleDbConnection = New OleDb.OleDbConnection(Me.ASSET_DSN)
        Dim dbCmdInsert As OleDb.OleDbCommand
        Dim dbCmdUpdate As OleDb.OleDbCommand
        Dim dbDA As OleDb.OleDbDataAdapter
        Dim curpos As Integer

        ' Save data: master_kategoriasset
        dbCmdInsert = New OleDb.OleDbCommand("as_MstKategoriasset_Insert", dbConn)
        dbCmdInsert.CommandType = CommandType.StoredProcedure
        dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@kategoriasset_id", System.Data.OleDb.OleDbType.VarWChar, 60, "kategoriasset_id"))
        dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@kategoriasset_time", System.Data.OleDb.OleDbType.Integer, 4, "kategoriasset_time"))
        dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@kategoriasset_depresiasitime", System.Data.OleDb.OleDbType.VarWChar, 100, "kategoriasset_depresiasitime"))
        dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@kategoriasset_depresiasivalue", System.Data.OleDb.OleDbType.Decimal, 9, System.Data.ParameterDirection.Input, False, CType(18, Byte), CType(0, Byte), "kategoriasset_depresiasivalue", System.Data.DataRowVersion.Current, Nothing))


        dbCmdUpdate = New OleDb.OleDbCommand("as_MstKategoriasset_Update", dbConn)
        dbCmdUpdate.CommandType = CommandType.StoredProcedure
        dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@kategoriasset_id", System.Data.OleDb.OleDbType.VarWChar, 60, "kategoriasset_id"))
        dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@kategoriasset_time", System.Data.OleDb.OleDbType.Integer, 4, "kategoriasset_time"))
        dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@kategoriasset_depresiasitime", System.Data.OleDb.OleDbType.VarWChar, 100, "kategoriasset_depresiasitime"))
        dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@kategoriasset_depresiasivalue", System.Data.OleDb.OleDbType.Decimal, 9, System.Data.ParameterDirection.Input, False, CType(18, Byte), CType(0, Byte), "kategoriasset_depresiasivalue", System.Data.DataRowVersion.Current, Nothing))


        dbDA = New OleDb.OleDbDataAdapter
        dbDA.UpdateCommand = dbCmdUpdate
        dbDA.InsertCommand = dbCmdInsert


        Try
            dbConn.Open()
            dbDA.Update(objTbl)

            kategoriasset_id = objTbl.Rows(0).Item("kategoriasset_id")
            Me.tbl_MstKategoriasset_Temp.Clear()
            Me.tbl_MstKategoriasset_Temp.Merge(objTbl)

        Catch ex As Data.OleDb.OleDbException
            MessageBox.Show(ex.Message, "OLE DB Error", MessageBoxButtons.OK, MessageBoxIcon.Error)
            Return False
        Catch ex As Exception
            MessageBox.Show(ex.Message)
            Return False
        Finally
            dbConn.Close()
        End Try


        If MasterDataState = DataRowState.Added Then
            Me.tbl_MstKategoriasset.Merge(objTbl)
        ElseIf MasterDataState = DataRowState.Modified Then
            curPos = Me.BindingContext(Me.tbl_MstKategoriasset).Position
            Me.tbl_MstKategoriasset.Rows.RemoveAt(curPos)
            Me.tbl_MstKategoriasset.Merge(objTbl)
        End If

        Me.BindingContext(Me.tbl_MstKategoriasset).Position = Me.BindingContext(Me.tbl_MstKategoriasset).Count

        Return True
    End Function

    Private Function uiMstKategoriAsset_Print() As Boolean
        'print data
    End Function

    Private Function uiMstKategoriAsset_Delete() As Boolean
        Dim res As String = ""
        Dim kategoriasset_id As Object = New Object

        Me.Cursor = Cursors.WaitCursor
        RaiseEvent FormBeforeDelete(kategoriasset_id)

        Me.Cursor = Cursors.WaitCursor
        If Me.DgvMstKategoriasset.CurrentRow IsNot Nothing Then

            res = MessageBox.Show("Are you sure want to delete data ?", mUiName, MessageBoxButtons.YesNo, MessageBoxIcon.Question)
            If res = DialogResult.Yes Then
                Me.uiMstKategoriAsset_DeleteRow(Me.DgvMstKategoriasset.CurrentRow.Index)
            End If

        End If

        RaiseEvent FormAfterDelete(kategoriasset_id)
        Me.Cursor = Cursors.Arrow

    End Function

    Private Function uiMstKategoriAsset_DeleteRow(ByVal rowIndex As Integer) As Boolean
        Dim dbConn As OleDb.OleDbConnection = New OleDb.OleDbConnection(Me.DSN)
        Dim dbCmdDelete As OleDb.OleDbCommand
        Dim kategoriasset_id As String
        Dim NewRowIndex As Integer

        kategoriasset_id = Me.DgvMstKategoriasset.Rows(rowIndex).Cells("kategoriasset_id").Value

        dbCmdDelete = New OleDb.OleDbCommand("as_MstKategoriasset_Delete", dbConn)
        dbCmdDelete.CommandType = CommandType.StoredProcedure
        dbCmdDelete.Parameters.Add(New System.Data.OleDb.OleDbParameter("@kategoriasset_id", System.Data.OleDb.OleDbType.VarWChar, 60))
        dbCmdDelete.Parameters("@kategoriasset_id").Value = kategoriasset_id
        dbCmdDelete.Parameters.Add(New System.Data.OleDb.OleDbParameter("@kategoriasset_time", System.Data.OleDb.OleDbType.Integer, 4))
        dbCmdDelete.Parameters("@kategoriasset_time").Value = DBNULL.value
        dbCmdDelete.Parameters.Add(New System.Data.OleDb.OleDbParameter("@kategoriasset_depresiasitime", System.Data.OleDb.OleDbType.VarWChar, 100))
        dbCmdDelete.Parameters("@kategoriasset_depresiasitime").Value = DBNULL.value
        dbCmdDelete.Parameters.Add(New System.Data.OleDb.OleDbParameter("@kategoriasset_depresiasivalue", System.Data.OleDb.OleDbType.Decimal, 9))
        dbCmdDelete.Parameters("@kategoriasset_depresiasivalue").Value = DBNULL.value

        Try
            dbConn.Open()
            dbCmdDelete.ExecuteNonQuery()

            If Me.DgvMstKategoriasset.Rows.Count > 1 Then

                If rowIndex = 0 Then
                    NewRowIndex = rowIndex + 1
                    Me.uiMstKategoriAsset_OpenRow(NewRowIndex)
                    Me.tbl_MstKategoriasset.Rows.RemoveAt(rowIndex)
                ElseIf rowIndex = Me.DgvMstKategoriasset.Rows.Count - 1 Then
                    NewRowIndex = rowIndex - 1
                    Me.uiMstKategoriAsset_OpenRow(NewRowIndex)
                    Me.tbl_MstKategoriasset.Rows.RemoveAt(rowIndex)
                Else
                    Me.tbl_MstKategoriasset.Rows.RemoveAt(rowIndex)
                    Me.uiMstKategoriAsset_OpenRow(rowIndex)
                End If

            Else

                Me.tbl_MstKategoriasset_Temp.Clear()
                Me.tbl_MstKategoriasset.Rows.RemoveAt(rowIndex)

            End If

        Catch ex As Data.OleDb.OleDbException
            MessageBox.Show(ex.Message, "OLE DB Error", MessageBoxButtons.OK, MessageBoxIcon.Error)
            Exit Function
        Catch ex As Exception
            MessageBox.Show(ex.Message)
            Exit Function
        Finally
            dbConn.Close()
        End Try
    End Function

    Private Function uiMstKategoriAsset_OpenRow(ByVal rowIndex As Integer) As Boolean
        Dim dbConn As OleDb.OleDbConnection = New OleDb.OleDbConnection(Me.ASSET_DSN)
        Dim kategoriasset_id As String

        kategoriasset_id = Me.DgvMstKategoriasset.Rows(rowIndex).Cells("kategoriasset_id").Value

        Me.Cursor = Cursors.WaitCursor
        RaiseEvent FormBeforeOpenRow(kategoriasset_id)


        Try
            dbConn.Open()
            Me.uiMstKategoriAsset_OpenRowMaster(kategoriasset_id, dbConn)
        Catch ex As Exception
            MessageBox.Show(ex.Message, mUiName & ": uiMstKategoriAsset_OpenRow()", MessageBoxButtons.OK, MessageBoxIcon.Error)
        Finally
            dbConn.Close()
        End Try

        RaiseEvent FormAfterOpenRow(kategoriasset_id)
        Me.Cursor = Cursors.Arrow

        Return True

    End Function

    Private Function uiMstKategoriAsset_OpenRowMaster(ByVal kategoriasset_id As String, ByVal dbConn As OleDb.OleDbConnection) As Boolean
        Dim dbCmd As OleDb.OleDbCommand
        Dim dbDA As OleDb.OleDbDataAdapter

        dbCmd = New OleDb.OleDbCommand("as_MstKategoriasset_Select", dbConn)
        dbCmd.Parameters.Add("@Criteria", Data.OleDb.OleDbType.VarChar)
        dbCmd.Parameters("@Criteria").Value = String.Format("kategoriasset_id='{0}'", kategoriasset_id)
        dbCmd.CommandType = CommandType.StoredProcedure
        dbDA = New OleDb.OleDbDataAdapter(dbCmd)
        Me.tbl_MstKategoriasset_Temp.Clear()

        Try
            Me.BindingStop()
            dbDA.Fill(Me.tbl_MstKategoriasset_Temp)
            Me.BindingStart()
        Catch ex As Exception
            Throw New Exception(mUiName & ": uiMstKategoriAsset_OpenRowMaster()" & vbCrLf & ex.Message)
        End Try

    End Function

    Private Function uiMstKategoriAsset_First() As Boolean
        'goto first record found
        Dim move As Boolean
        Dim Message As String = "Data has been changed. " & vbCrLf & "Save data changes before move to first record ?"
        Dim iTab As Integer = Me.ftabMain.SelectedIndex

        If iTab = 1 Then
            If Me.DATA_ISLOCKED Then
                move = True
            Else
                move = Me.uiMstKategoriAsset_ConfirmSaveBeforeMove(Message)
            End If
        Else
            move = True
        End If

        If move Then
            Me.DgvMstKategoriasset.CurrentCell = Me.DgvMstKategoriasset(1, 0)
            Me.uiMstKategoriAsset_RefreshPosition()
        End If
    End Function

    Private Function uiMstKategoriAsset_Prev() As Boolean
        'goto previous record found
        Dim move As Boolean
        Dim Message As String = "Data has been changed. " & vbCrLf & "Save data changes before move to previous record ?"
        Dim iTab As Integer = Me.ftabMain.SelectedIndex

        If iTab = 1 Then
            If Me.DATA_ISLOCKED Then
                move = True
            Else
                move = Me.uiMstKategoriAsset_ConfirmSaveBeforeMove(Message)
            End If
        Else
            move = True
        End If

        If move Then
            If Me.DgvMstKategoriasset.CurrentCell.RowIndex > 0 Then
                Me.DgvMstKategoriasset.CurrentCell = Me.DgvMstKategoriasset(1, DgvMstKategoriasset.CurrentCell.RowIndex - 1)
                Me.uiMstKategoriAsset_RefreshPosition()
            End If
        End If
    End Function

    Private Function uiMstKategoriAsset_Next() As Boolean
        'goto next record found
        Dim move As Boolean
        Dim Message As String = "Data has been changed. " & vbCrLf & "Save data changes before move to next record ?"
        Dim iTab As Integer = Me.ftabMain.SelectedIndex

        If iTab = 1 Then
            If Me.DATA_ISLOCKED Then
                move = True
            Else
                move = Me.uiMstKategoriAsset_ConfirmSaveBeforeMove(Message)
            End If
        Else
            move = True
        End If

        If move Then
            If Me.DgvMstKategoriasset.CurrentCell.RowIndex < Me.DgvMstKategoriasset.Rows.Count - 1 Then
                Me.DgvMstKategoriasset.CurrentCell = Me.DgvMstKategoriasset(1, DgvMstKategoriasset.CurrentCell.RowIndex + 1)
                Me.uiMstKategoriAsset_RefreshPosition()
            End If
        End If
    End Function

    Private Function uiMstKategoriAsset_Last() As Boolean
        'goto last record found
        Dim move As Boolean
        Dim Message As String = "Data has been changed. " & vbCrLf & "Save data changes before move to next record ?"
        Dim iTab As Integer = Me.ftabMain.SelectedIndex

        If iTab = 1 Then
            If Me.DATA_ISLOCKED Then
                move = True
            Else
                move = Me.uiMstKategoriAsset_ConfirmSaveBeforeMove(Message)
            End If
        Else
            move = True
        End If

        If move Then
            Me.DgvMstKategoriasset.CurrentCell = Me.DgvMstKategoriasset(1, Me.DgvMstKategoriasset.Rows.Count - 1)
            Me.uiMstKategoriAsset_RefreshPosition()
        End If
    End Function

    Private Function uiMstKategoriAsset_RefreshPosition() As Boolean
        'refresh position
        Dim iTab As Integer = Me.ftabMain.SelectedIndex
        If iTab = 1 Then uiMstKategoriAsset_OpenRow(Me.DgvMstKategoriasset.CurrentRow.Index)
    End Function

    Private Function uiMstKategoriAsset_ConfirmSaveBeforeMove(ByVal Message As String) As Boolean
        'confirm saving data changes before move
        Dim tbl_MstKategoriasset_Temp_Changes As DataTable
        Dim res As System.Windows.Forms.DialogResult
        Dim success As Boolean
        Dim i As Integer = 0
        Dim MasterDataState As System.Data.DataRowState
        Dim kategoriasset_id As Object = New Object
        Dim move As Boolean = False
        Dim result As FormSaveResult


        If Me.DgvMstKategoriasset.CurrentCell IsNot Nothing Then

            Me.BindingContext(Me.tbl_MstKategoriasset_Temp).EndCurrentEdit()
            tbl_MstKategoriasset_Temp_Changes = Me.tbl_MstKategoriasset_Temp.GetChanges()

            If tbl_MstKategoriasset_Temp_Changes IsNot Nothing Then

                res = MessageBox.Show(Message, mUiName, MessageBoxButtons.YesNoCancel, MessageBoxIcon.Question)
                Select Case res
                    Case DialogResult.Yes

                        RaiseEvent FormBeforeSave(kategoriasset_id)

                        Try

                            If tbl_MstKategoriasset_Temp_Changes IsNot Nothing Then
                                success = Me.uiMstKategoriAsset_SaveMaster(kategoriasset_id, tbl_MstKategoriasset_Temp_Changes, MasterDataState)
                                If Not success Then Throw New Exception("Cannot Save Master Data")
                                Me.tbl_MstKategoriasset_Temp.AcceptChanges()
                            End If

                            result = FormSaveResult.SaveSuccess
                            If SHOW_SAVE_CONFIRMATION Then
                                MessageBox.Show("Data Saved", mUiName, MessageBoxButtons.OK, MessageBoxIcon.Information)
                            End If

                        Catch ex As Exception
                            result = FormSaveResult.SaveError
                            MessageBox.Show(ex.Message & vbCrLf & "Data Cannot Be Saved", mUiName, MessageBoxButtons.OK, MessageBoxIcon.Error)
                        End Try

                        RaiseEvent FormAfterSave(kategoriasset_id, result)

                    Case DialogResult.No
                        move = True
                    Case DialogResult.Cancel
                        move = False
                End Select
            Else
                move = True
            End If

        End If

        Return move

    End Function

    Private Function uiMstKategoriAsset_FormError() As Boolean
        Try
            ' TODO: Cek Error disini
            ' objFormError.SetError()

            ' Throw New Exception("Error")
        Catch ex As Exception
            MessageBox.Show(ex.Message, mUiName, MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
            Return True
        End Try
        Return False
    End Function

#End Region



    Private Sub uiMstKategoriAsset_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load

        Dim objParameters As Collection = New Collection
        'TODO: - Extract Parameter
        '      - Assign parameter
        If Me.Browser IsNot Nothing Then
            objParameters = Me.GetParameterCollection(Me.Parameter)
        End If

        Me.InitLayoutUI()

        Me.DgvMstKategoriasset.DataSource = Me.tbl_MstKategoriasset
        If (Me.Browser IsNot Nothing And MyBase.Name = "MainControl") Or (Me.Browser Is Nothing And Application.ProductName <> "TransBrowser") Then
            'Fill Combobox
            'dan fungsi2 startup lainnya....
            Me.ComboFill(Me.obj_Kategoriasset_depresiasitime, "Pilihan", "Pilihan", Me.tbl_MstKategoriassetpilihan, "as_pilihanMstKategoriasset_Select", " kategori = 'Mstkategoriasset' and is_disable = 0")
            'Me.obj_Kategoriasset_depresiasitime.de.Sort = "pilihan"
        End If

        Me.BindingStop()
        Me.BindingStart()

        Me.uiMstKategoriAsset_NewData()

        Me.tbtnSave.Enabled = False
        Me.tbtnDel.Enabled = False
        Me.tbtnLoad.Enabled = True
        Me.tbtnQuery.Enabled = True


    End Sub

    Private Sub ftabMain_SelectedIndexChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles ftabMain.SelectedIndexChanged

        Select Case ftabMain.SelectedIndex
            Case 0
                Me.tbtnSave.Enabled = False
                Me.tbtnDel.Enabled = False
                Me.tbtnLoad.Enabled = True
                Me.tbtnQuery.Enabled = True
                Me.ftabMain.TabPages.Item(0).BackColor = Color.Linen
                Me.ftabMain.TabPages.Item(1).BackColor = Color.White

            Case 1
                Me.tbtnSave.Enabled = True
                Me.tbtnDel.Enabled = True
                Me.tbtnLoad.Enabled = False
                Me.tbtnQuery.Enabled = False
                Me.ftabMain.TabPages.Item(0).BackColor = Color.White
                Me.ftabMain.TabPages.Item(1).BackColor = Color.Linen
                'MsgBox(Me.DgvMstKategoriasset.Item(0, Me.DgvMstKategoriasset.CurrentRow.Index).Value)
                If Me.DgvMstKategoriasset.CurrentRow IsNot Nothing Then
                    ' Me.uiMstKategoriAsset_OpenRow(Me.DgvMstKategoriasset.Item(0, Me.DgvMstKategoriasset.CurrentRow.Index).Value)
                    Me.uiMstKategoriAsset_OpenRow(Me.DgvMstKategoriasset.CurrentRow.Index)
                Else
                    Me.uiMstKategoriAsset_NewData()
                End If


        End Select
    End Sub

    Private Sub DgvMstKategoriasset_CellDoubleClick(ByVal sender As Object, ByVal e As System.Windows.Forms.DataGridViewCellEventArgs) Handles DgvMstKategoriasset.CellDoubleClick
        If e.ColumnIndex < 0 Or e.RowIndex < 0 Then
            Exit Sub
        End If
        If Me.DgvMstKategoriasset.CurrentRow IsNot Nothing Then
            Me.ftabMain.SelectedIndex = 1
        End If
    End Sub





End Class